import { useState } from "react";
import { Link, useLocation, useNavigate } from "react-router-dom";
import { ArrowRight, Loader2 } from "lucide-react";
import { useAuth } from "../auth";
import Logo from "../components/Logo";

export default function AuthPage({mode}){
  const register = mode === "register"; const {login,register:signup}=useAuth(); const navigate=useNavigate(); const location=useLocation();
  const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
  async function submit(e){e.preventDefault();setError("");setBusy(true);try{if(register)await signup(email.trim(),password);else await login(email.trim(),password);navigate(location.state?.from?.pathname||"/app",{replace:true});}catch(err){setError(err.message);setBusy(false)}}
  function demo(){localStorage.setItem("verifyai_demo_user",JSON.stringify({email:"demo@verifyai.local"}));window.location.href="/app";}
  return <div className="auth-page"><section className="auth-showcase"><Link to="/"><Logo dark/></Link><div className="auth-showcase-copy"><span className="eyebrow" style={{background:'rgba(255,255,255,.1)',borderColor:'rgba(255,255,255,.18)',color:'#fff'}}>Evidence-first research</span><h1>Research deserves more than a black-box answer.</h1><p>VerifyAI is designed to make claims, sources, verdicts and AI analysis understandable at a glance.</p></div><div className="auth-proof"><div><b>30+</b><span>claims per paper</span></div><div><b>Evidence</b><span>source context</span></div><div><b>AI + Research</b><span>one workspace</span></div></div></section><section className="auth-panel"><div className="auth-card"><Link to="/"><Logo/></Link><h2>{register?"Create your workspace":"Welcome back"}</h2><p>{register?"Set up your VerifyAI workspace. Evidence-grounded verification and AI analysis are connected to the VerifyAI backend.":"Continue to your research verification workspace."}</p>{error&&<div className="form-error">{error}</div>}<form onSubmit={submit}><div className="form-group"><label>Email</label><input className="input" type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></div><div className="form-group"><label>Password</label><input className="input" type="password" required minLength={register?8:undefined} value={password} onChange={e=>setPassword(e.target.value)} placeholder="••••••••"/></div><button className="btn btn-primary" style={{width:'100%',marginTop:20}} disabled={busy}>{busy?<Loader2 className="spinner" size={16}/>:<ArrowRight size={16}/>} {register?"Create account":"Log in"}</button></form><button className="btn btn-secondary" style={{width:'100%',marginTop:10}} onClick={demo}>Preview the frontend</button><div className="auth-switch">{register?"Already have an account? ":"Don't have an account? "}<Link to={register?"/login":"/register"} style={{color:'var(--brand)',fontWeight:800}}>{register?"Log in":"Create one"}</Link></div></div></section></div>
}
