import { ArrowRight, CheckCircle2, FileCheck2, Search, ShieldCheck, Sparkles } from "lucide-react";
import { Link } from "react-router-dom";
import Logo from "../components/Logo";

export default function LandingPage() {
  return <div className="landing">
    <header className="public-nav"><div className="nav-inner"><Link to="/"><Logo/></Link><nav className="nav-links"><a href="#features">Features</a><a href="#how">How it works</a><a href="#trust">Trust</a></nav><div style={{display:'flex',gap:8}}><Link className="btn btn-ghost" to="/login">Log in</Link><Link className="btn btn-primary" to="/register">Start verifying <ArrowRight size={15}/></Link></div></div></header>
    <section className="hero"><div className="hero-grid"><div><span className="eyebrow"><Sparkles size={13}/> Research intelligence, redesigned</span><h1>Verify research with <span className="gradient-text">confidence.</span></h1><p>VerifyAI brings research claims, evidence, AI-content analysis and clear verdicts into one focused workspace.</p><div className="hero-actions"><Link className="btn btn-primary" to="/register">Start verifying <ArrowRight size={15}/></Link><Link className="btn btn-secondary" to="/login">Explore the workspace</Link></div><div className="hero-note">Designed for evidence-first research workflows.</div></div><div className="hero-visual"><div className="preview-shell"><div className="preview-top"><div className="preview-dots"><i/><i/><i/></div><span>verifyai.app</span></div><div className="preview-body"><div className="preview-side"><strong>VerifyAI</strong><div className="preview-nav"><span>Dashboard</span><span>AI Detector</span><span>Research</span><span>Reports</span><span>History</span><span>Settings</span></div></div><div className="preview-main"><div className="preview-heading"/><div className="preview-cards"><div className="preview-card"><b>84%</b><small>Verified</small></div><div className="preview-card"><b>30</b><small>Claims</small></div><div className="preview-card"><b>18</b><small>Supported</small></div></div><div className="preview-panel"><div className="fake-chart"/></div></div></div></div></div></div></section>
    <section className="section" id="features"><div className="section-head"><span className="eyebrow">Built around evidence</span><h2>One workspace for the questions that matter.</h2><p>VerifyAI is structured around clear claims, transparent evidence and understandable outcomes—not black-box scores.</p></div><div className="feature-grid"><Feature icon={FileCheck2} title="Research verification" text="Turn papers into atomic claims and review the evidence behind each result."/><Feature icon={Sparkles} title="AI content detection" text="Analyze pasted text or documents with a focused AI-versus-human analysis experience."/><Feature icon={ShieldCheck} title="Evidence-first results" text="Keep verdicts, confidence and source context visible together so reasoning stays inspectable."/></div></section>
    <section className="section" id="how"><div className="section-head"><span className="eyebrow">How it works</span><h2>From document to defensible result.</h2></div><div className="how-grid"><Step n="01" title="Upload or paste" text="Bring in a research paper, text, or AI-generated content."/><Step n="02" title="Extract and inspect" text="Claims become a structured workspace you can review and filter."/><Step n="03" title="Verify with evidence" text="Sources and verdicts sit side by side for a clear final report."/></div></section>
    <section className="section" id="trust"><div className="card" style={{padding:32,background:'linear-gradient(135deg,var(--surface),var(--brand-soft))'}}><div style={{display:'flex',gap:18,alignItems:'flex-start'}}><div className="feature-icon"><CheckCircle2 size={21}/></div><div><h2 style={{margin:'0 0 8px',fontSize:24}}>The LLM reasons over evidence. The LLM is not the evidence.</h2><p style={{margin:0,color:'var(--muted)',lineHeight:1.7,fontSize:13}}>That principle will guide the backend and LLM phases later. For now, the frontend is designed around the same transparent workflow.</p></div></div></div></section>
    <footer className="public-footer"><div className="public-footer-inner"><span>© 2026 VerifyAI</span><span>Research with Confidence</span></div></footer>
  </div>;
}
function Feature({icon:Icon,title,text}){return <article className="feature-card"><div className="feature-icon"><Icon size={20}/></div><h3>{title}</h3><p>{text}</p></article>}
function Step({n,title,text}){return <article className="how-item"><div className="how-num">{n}</div><h3>{title}</h3><p>{text}</p></article>}
